MortgageCalc/force-app/main/default/objects/MortgageCalculator__c/MortgageCalculator__c.object-meta.xml
<CustomObject>
    <label>MortgageCalculator</label>
    <nameField>
        <label>MortgageCalculator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MortgageCalculators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MortgageCalc/force-app/main/default/objects/MortgageCalculator__c/fields/Down_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Down_Payment_Amount__c</fullName>
    <label>Down Payment Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

MortgageCalc/force-app/main/default/objects/MortgageCalculator__c/fields/insurance__c.field-meta.xml
<CustomField>
    <fullName>insurance__c</fullName>
    <label>insurance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MortgageCalc/force-app/main/default/objects/MortgageCalculator__c/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

MortgageCalc/force-app/main/default/objects/MortgageCalculator__c/fields/Length_of_loan__c.field-meta.xml
<CustomField>
    <fullName>Length_of_loan__c</fullName>
    <label>Length of loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30 Years, 20 Years, 15 Years, 10 Years</fullName>
                <default>true</default>
                <label>30 Years, 20 Years, 15 Years, 10 Years</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MortgageCalc/force-app/main/default/objects/MortgageCalculator__c/fields/tax__c.field-meta.xml
<CustomField>
    <fullName>tax__c</fullName>
    <label>tax</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MortgageCalc/force-app/main/default/classes/backEndCalc.cls
public with sharing class backEndCalc {
    @AuraEnabled
    public static MortgageCalculator__c backEndCalc(MortgageCalculator__c, morgCalc) {
        int n = morgCalc.Length_of_loan__c * 12;
        int i = (morgCalc.Interest__c / 100) / 12;
        int d = (((1 + i) ** n) - 1) / (i * ((1 + i) ** n));
        
        int monthly  = (morgCalc.Price__c - morgCalc.Down_Payment_Amount__c) / d;
        int final = (monthly + morgCalc.insurance__c + morgCalc.tax__c);

        return final;
    }
}